module.exports = {
  ANALYTICS_NO_GENRE: 'ANALYTICS_NO_GENRE',
  FILE_ERROR: 'FILE_ERROR',
  FILES_TO_PROCESS: 'FILES_TO_PROCESS',
  FILES_TO_IGNORE: 'FILES_TO_IGNORE',
  FILE_NEW: 'FILE_NEW',
  FILE_NO_CHANGE: 'FILE_NO_CHANGE',
  FILE_CHANGED: 'FILE_CHANGED',
  FILE_TO_DELETE_FROM_TARGET: 'FILE_TO_DELETE_FROM_TARGET'
};
